_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_DENSEPOSE_HEAD:
    NUM_COARSE_SEGM_CHANNELS: 15
    POOLER_RESOLUTION: 14
    HEATMAP_SIZE: 56
    INDEX_WEIGHTS: 2.0
    PART_WEIGHTS: 0.3
    POINT_REGRESSION_WEIGHTS: 0.1
    DECODER_ON: False
SOLVER:
  BASE_LR: 0.002
  MAX_ITER: 130000
  STEPS: (100000, 120000)
INPUT:
  SVG:
    LOAD_SVG: True
    AUG: True
    AUG_PROB_JOINTS: 0.4
    AUG_PROB_LIMBS_OCC: 0.7
    AUG_PROB_LIMBS_VIS: 0.2
    AUG_PROB_TORSO_OCC: 0.7
    AUG_PROB_TORSO_VIS: 0.2
DATASETS:
  TRAIN: ("densepose_coco_2014_train", "densepose_coco_2014_valminusminival")
  TEST: ("densepose_coco_2014_minival", "densepose_coco_2014_testreal_g", "densepose_coco_2014_testreal_m")
